package tarea03;
// Generated Dec 25, 2023, 1:15:08 PM by Hibernate Tools 6.3.1.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Departamentos generated by hbm2java
 */
public class Departamentos implements java.io.Serializable {

	private BigInteger codDepar;
	private String nombreDepar;
	private BigInteger numAsig;
	private Set asignaturases = new HashSet(0);

	public Departamentos() {
	}

	public Departamentos(BigInteger codDepar, String nombreDepar, BigInteger numAsig, Set asignaturases) {
		this.codDepar = codDepar;
		this.nombreDepar = nombreDepar;
		this.numAsig = numAsig;
		this.asignaturases = asignaturases;
	}

	public BigInteger getCodDepar() {
		return this.codDepar;
	}

	public void setCodDepar(BigInteger codDepar) {
		this.codDepar = codDepar;
	}

	public String getNombreDepar() {
		return this.nombreDepar;
	}

	public void setNombreDepar(String nombreDepar) {
		this.nombreDepar = nombreDepar;
	}

	public BigInteger getNumAsig() {
		return this.numAsig;
	}

	public void setNumAsig(BigInteger numAsig) {
		this.numAsig = numAsig;
	}

	public Set getAsignaturases() {
		return this.asignaturases;
	}

	public void setAsignaturases(Set asignaturases) {
		this.asignaturases = asignaturases;
	}

}
