package tarea03;
// Generated Dec 25, 2023, 1:15:08 PM by Hibernate Tools 6.3.1.Final

import java.math.BigInteger;

/**
 * EvaluacionesId generated by hbm2java
 */
public class EvaluacionesId implements java.io.Serializable {

	private BigInteger codAsig;
	private BigInteger codEvaluacion;
	private BigInteger numAlumno;

	public EvaluacionesId() {
	}

	public EvaluacionesId(BigInteger codAsig, BigInteger codEvaluacion, BigInteger numAlumno) {
		this.codAsig = codAsig;
		this.codEvaluacion = codEvaluacion;
		this.numAlumno = numAlumno;
	}

	public BigInteger getCodAsig() {
		return this.codAsig;
	}

	public void setCodAsig(BigInteger codAsig) {
		this.codAsig = codAsig;
	}

	public BigInteger getCodEvaluacion() {
		return this.codEvaluacion;
	}

	public void setCodEvaluacion(BigInteger codEvaluacion) {
		this.codEvaluacion = codEvaluacion;
	}

	public BigInteger getNumAlumno() {
		return this.numAlumno;
	}

	public void setNumAlumno(BigInteger numAlumno) {
		this.numAlumno = numAlumno;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EvaluacionesId))
			return false;
		EvaluacionesId castOther = (EvaluacionesId) other;

		return ((this.getCodAsig() == castOther.getCodAsig()) || (this.getCodAsig() != null
				&& castOther.getCodAsig() != null && this.getCodAsig().equals(castOther.getCodAsig())))
				&& ((this.getCodEvaluacion() == castOther.getCodEvaluacion())
						|| (this.getCodEvaluacion() != null && castOther.getCodEvaluacion() != null
								&& this.getCodEvaluacion().equals(castOther.getCodEvaluacion())))
				&& ((this.getNumAlumno() == castOther.getNumAlumno()) || (this.getNumAlumno() != null
						&& castOther.getNumAlumno() != null && this.getNumAlumno().equals(castOther.getNumAlumno())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodAsig() == null ? 0 : this.getCodAsig().hashCode());
		result = 37 * result + (getCodEvaluacion() == null ? 0 : this.getCodEvaluacion().hashCode());
		result = 37 * result + (getNumAlumno() == null ? 0 : this.getNumAlumno().hashCode());
		return result;
	}

}
