package tarea03;
// Generated Dec 25, 2023, 1:15:08 PM by Hibernate Tools 6.3.1.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Asignaturas generated by hbm2java
 */
public class Asignaturas implements java.io.Serializable {

	private BigInteger codAsig;
	private Departamentos departamentos;
	private Cursos cursos;
	private String nombre;
	private Set evaluacioneses = new HashSet(0);

	public Asignaturas() {
	}

	public Asignaturas(BigInteger codAsig, Departamentos departamentos, Cursos cursos, String nombre,
			Set evaluacioneses) {
		this.codAsig = codAsig;
		this.departamentos = departamentos;
		this.cursos = cursos;
		this.nombre = nombre;
		this.evaluacioneses = evaluacioneses;
	}

	public BigInteger getCodAsig() {
		return this.codAsig;
	}

	public void setCodAsig(BigInteger codAsig) {
		this.codAsig = codAsig;
	}

	public Departamentos getDepartamentos() {
		return this.departamentos;
	}

	public void setDepartamentos(Departamentos departamentos) {
		this.departamentos = departamentos;
	}

	public Cursos getCursos() {
		return this.cursos;
	}

	public void setCursos(Cursos cursos) {
		this.cursos = cursos;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getEvaluacioneses() {
		return this.evaluacioneses;
	}

	public void setEvaluacioneses(Set evaluacioneses) {
		this.evaluacioneses = evaluacioneses;
	}

}
