package tarea03;
// Generated Dec 25, 2023, 1:15:08 PM by Hibernate Tools 6.3.1.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Cursos generated by hbm2java
 */
public class Cursos implements java.io.Serializable {

	private BigInteger codCurso;
	private Centros centros;
	private String denominacion;
	private Integer costeMatricula;
	private BigInteger numAlumnos;
	private Set asignaturases = new HashSet(0);
	private Set alumnoses = new HashSet(0);

	public Cursos() {
	}

	public Cursos(BigInteger codCurso, Centros centros, String denominacion, Integer costeMatricula,
			BigInteger numAlumnos, Set asignaturases, Set alumnoses) {
		this.codCurso = codCurso;
		this.centros = centros;
		this.denominacion = denominacion;
		this.costeMatricula = costeMatricula;
		this.numAlumnos = numAlumnos;
		this.asignaturases = asignaturases;
		this.alumnoses = alumnoses;
	}

	public BigInteger getCodCurso() {
		return this.codCurso;
	}

	public void setCodCurso(BigInteger codCurso) {
		this.codCurso = codCurso;
	}

	public Centros getCentros() {
		return this.centros;
	}

	public void setCentros(Centros centros) {
		this.centros = centros;
	}

	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	public Integer getCosteMatricula() {
		return this.costeMatricula;
	}

	public void setCosteMatricula(Integer costeMatricula) {
		this.costeMatricula = costeMatricula;
	}

	public BigInteger getNumAlumnos() {
		return this.numAlumnos;
	}

	public void setNumAlumnos(BigInteger numAlumnos) {
		this.numAlumnos = numAlumnos;
	}

	public Set getAsignaturases() {
		return this.asignaturases;
	}

	public void setAsignaturases(Set asignaturases) {
		this.asignaturases = asignaturases;
	}

	public Set getAlumnoses() {
		return this.alumnoses;
	}

	public void setAlumnoses(Set alumnoses) {
		this.alumnoses = alumnoses;
	}

}
